image: docker:latest

services:
  - docker:dind

variables:
  PROJECT_NAME: api-docs

stages:
  - deploy

deploy:
  stage: deploy
  script:
    - docker build -t $PROJECT_NAME .
    - docker run -e "AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID" -e "AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY" -e "AWS_DEFAULT_REGION=$AWS_DEFAULT_REGION" api-docs
  only:
    - master
